ConferenceFormSubmittal/Models/Application.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ConferenceFormSubmittal.Models
{
    public class Application
    {
        public Application()
        {
            Mileages = new HashSet<Mileage>();
            Expenses = new HashSet<Expense>();
        }

        public int ID { get; set; }

        [StringLength(500, ErrorMessage = "Rationale may include a maximum of 500 characters.")]
        [DataType(DataType.MultilineText)]
        public string Rationale { get; set; }

        [Display(Name = "Replacement Staff Required")]
        public bool ReplStaffReq { get; set; }

        [Display(Name = "Budget Code")]
        public string BudgetCode { get; set; }

        // The date on which they will travel to the conference
        [Display(Name = "Departure Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? DepartureDate { get; set; }

        // The date on which they will return from the conference
        [Display(Name = "Return Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ReturnDate { get; set; }

        // The first day they will attend the conference
        [Display(Name = "Start of Attendance")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? AttendStartDate { get; set; }

        // The last day they will attend the conference
        [Display(Name = "End of Attendance")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? AttendEndDate { get; set; }

        // The actual submission date (Applications can be saved as drafts)
        [Display(Name = "Date Submitted")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime? DateSubmitted { get; set; }

        // Administrator feedback
        [StringLength(500, ErrorMessage = "Feedback may include a maximum of 500 characters.")]
        [DataType(DataType.MultilineText)]
        public string Feedback { get; set; }

        [Display(Name = "Employee")]
        public int EmployeeID { get; set; } = 1; // Using default value until user roles are implemented

        [Display(Name = "Conference")]
        public int ConferenceID { get; set; }

        [Display(Name = "Status")]
        public int StatusID { get; set; }

        [Display(Name = "Payment Type")]
        public int? PaymentTypeID { get; set; }

        public virtual Employee Employee { get; set; }

        public virtual Conference Conference { get; set; }

        public virtual Status Status { get; set; }

        public virtual PaymentType PaymentType { get; set; }

        public virtual ICollection<Mileage> Mileages { get; set; }

        public virtual ICollection<Expense> Expenses { get; set; }
    }
}

ConferenceFormSubmittal/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConferenceFormSubmittal.DAL;
using ConferenceFormSubmittal.Models;
using System.Data.Entity.Infrastructure;
using PagedList;

namespace ConferenceFormSubmittal.Controllers
{
    public class ApplicationsController : Controller
    {
        private CFSEntities db = new CFSEntities();

        // GET: Applications
        public ActionResult Index(string sortDirection, string sortField, string actionButton,
            DateTime? startDate, DateTime? endDate, string conferenceName, int? statusID, int? page)
        {
            PopulateDropDownLists();
            var applications = db.Applications.Include(a => a.Conference).Include(a => a.Employee).Include(a => a.Status);
            ViewBag.Filtering = "";
            
            if (startDate.HasValue && endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted > startDate && p.DateSubmitted < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
                ViewBag.LastEndDate = endDate;
            }
            else if (startDate.HasValue && !endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted > startDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
            }
            else if (!startDate.HasValue && endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndDate = endDate;
            }
            if (!String.IsNullOrEmpty(conferenceName))
            {
                applications = applications.Where(p => p.Conference.Name.ToUpper().Contains(conferenceName.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastConferenceName = conferenceName;
            }
            if (statusID.HasValue)
            {
                applications = applications.Where(p => p.StatusID == statusID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStatusID = statusID;
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = String.IsNullOrEmpty(sortDirection) ? "desc" : "";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            if (sortField == "Date Submitted")//Sorting by Date Submitted
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(p => p.DateSubmitted);
                }
                else
                {
                    applications = applications
                        .OrderByDescending(p => p.DateSubmitted);
                }
            }
            else if (sortField == "Conference Name")//Sorting by Conference Name
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(c => c.Conference.Name);
                }
                else
                {
                    applications = applications.OrderByDescending(c => c.Conference.Name);
                }
            }
            else //By default sort by Status
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(c => c.StatusID);
                }
                else
                {
                    applications = applications.OrderByDescending(c => c.StatusID);
                }
            }

            ViewBag.sortField = sortField;
            ViewBag.sortDirection = sortDirection;

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(applications.ToPagedList(pageNumber, pageSize));
        }

        // GET: Applications
        public ActionResult IndexAdmin(string sortDirection, string sortField, string actionButton,
            int? employeeID, string employeeFirst, string employeeLast, DateTime? startDate,
            DateTime? endDate, string conferenceName, int? statusID, int? page)
        {
            PopulateDropDownLists();
            var applications = db.Applications.Include(a => a.Conference).Include(a => a.Employee).Include(a => a.Status);
            ViewBag.Filtering = "";

            if (employeeID.HasValue)
            {
                applications = applications.Where(p => p.EmployeeID == employeeID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeID = employeeID;
            }
            if (!String.IsNullOrEmpty(employeeFirst))
            {
                applications = applications.Where(p => p.Employee.FirstName.ToUpper().Contains(employeeFirst.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeName = employeeFirst;
            }
            if (!String.IsNullOrEmpty(employeeLast))
            {
                applications = applications.Where(p => p.Employee.LastName.ToUpper().Contains(employeeLast.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeName = employeeLast;
            }
            if (startDate.HasValue && endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted > startDate && p.DateSubmitted < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
                ViewBag.LastEndDate = endDate;
            }
            else if (startDate.HasValue && !endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted > startDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
            }
            else if (!startDate.HasValue && endDate.HasValue)
            {
                applications = applications.Where(p => p.DateSubmitted < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndDate = endDate;
            }
            if (!String.IsNullOrEmpty(conferenceName))
            {
                applications = applications.Where(p => p.Conference.Name.ToUpper().Contains(conferenceName.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastConferenceName = conferenceName;
            }
            if (statusID.HasValue)
            {
                applications = applications.Where(p => p.StatusID == statusID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStatusID = statusID;
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = String.IsNullOrEmpty(sortDirection) ? "desc" : "";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            if (sortField == "Employee")//Sorting by Employee Name
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(c => c.Employee.LastName)
                        .ThenBy(p => p.Employee.FirstName);
                }
                else
                {
                    applications = applications
                        .OrderByDescending(c => c.Employee.LastName)
                        .ThenByDescending(c => c.Employee.FirstName);
                }
            }
            else if (sortField == "Date Submitted")//Sorting by Date Submitted
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(p => p.DateSubmitted);
                }
                else
                {
                    applications = applications
                        .OrderByDescending(p => p.DateSubmitted);
                }
            }
            else if (sortField == "Conference Name")//Sorting by Conference Name
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(c => c.Conference.Name);
                }
                else
                {
                    applications = applications.OrderByDescending(c => c.Conference.Name);
                }
            }
            else //By default sort by Status
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    applications = applications
                        .OrderBy(c => c.StatusID);
                }
                else
                {
                    applications = applications.OrderByDescending(c => c.StatusID);
                }
            }

            ViewBag.sortField = sortField;

ConferenceFormSubmittal/Views/Applications/Delete.cshtml
@model ConferenceFormSubmittal.Models.Application

@{
    ViewBag.Title = "Delete";
}



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <!--HEADING-->
        <div class="row pt-3">
            <div class="col-12">
                <div class="card card-header bg-NCDSB-Grey">
                    <h3 class="text-center font-weight-bold">Application Details</h3>
                </div>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-3">
                <div class="card card-body bg-NCDSB-Grey">
                    <div class="col-12">
                        <input type="submit" value="Delete" class="btn btn-danger btn-block mt-2" />

                        <b class="d-block mt-3">Employee Name</b>
                        @Html.DisplayFor(model => model.Employee.FullName)

                        <b class="d-block mt-2">Conference Name</b>
                        @*@Html.DisplayNameFor(model => model.Conference.Name)*@
                        @Html.DisplayFor(model => model.Conference.Name)

                        <b class="d-block mt-2">Status</b>
                        @Html.DisplayFor(model => model.Status.Description)

                        <b class="d-block mt-2">Require Repl Staff</b>
                        @Html.DisplayFor(model => model.ReplStaffReq)

                        <b class="d-block mt-2">Budget Code</b>
                        @Html.DisplayFor(model => model.BudgetCode)

                        <b class="d-block mt-2">Date Submitted</b>
                        @Html.DisplayFor(model => model.DateSubmitted)

                        @Html.ActionLink("Back to List", "Index", "Applications", null, new { @class = "btn btn-primary btn-block mt-3" })


                    </div>
                </div>
            </div> <!--col-->

            <div class="col-9">
                <div class="card card-body bg-NCDSB-Grey">
                    <div class="col-12">
                        <b class="d-block mt-2">Rationale</b>
                        @Html.DisplayFor(model => model.Rationale)

                        <b class="d-block mt-2">Feedback</b>
                        @Html.DisplayFor(model => model.Feedback)

                        @{if (Model.StatusID == 1)
                            {
                                <b class="d-block mt-2">Expenses</b>

                                {
                                    foreach (var item in Model.Expenses)
                                    {
                                        @item.ExpenseType.Description <br />
                                    }
                                }
                            }
                        }
                    </div>
                </div>
            </div> <!--col-->
        </div>
    }

ConferenceFormSubmittal/Views/Applications/Details.cshtml
@model ConferenceFormSubmittal.Models.Application
@using ConferenceFormSubmittal.Utilities;

@{
    ViewBag.Title = "Details";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Application Details</h3>

        </div>
    </div>
</div>

@*//------------------------------------------------ Header buttons ---------------------------------*@
<div class="row mt-3">
    <div class="col-12">

        <div class="card bg-NCDSB-Grey">
            <div class="card-header">
                <div class="row ">
                    <div class="col-12 d-flex justify-content-between">
                        <a href='@Url.Action("Index", "Applications")' class="btn btn-primary">
                            @Helper.GetIcon(Icons.Back)
                            Go Back
                        </a>

                        <a href='@Url.Action("Edit", "Applications", new { id = Model.ID })' class="btn btn-info">
                            @Helper.GetIcon(Icons.Edit)
                            Edit
                        </a>

                        <a href='@Url.Action("Delete", "Applications", new { id = Model.ID })' class="btn btn-danger">
                            @Helper.GetIcon(Icons.Flag)
                            Flag
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@*-----------------------------------------------------Conference Details ----------------------------------------*@
<div class="row mt-3">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey">
            <div class="card-header" ">
                <h4>Conference Details</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        @Html.LabelFor(model => model.ConferenceID, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Conference.Name)
                    </div>

                    <div class="col-6">

                        @Html.LabelFor(model => model.Conference.Location, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Conference.Location)

                    </div>

                </div>

                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.Conference.StartDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Conference.StartDate)
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.Conference.EndDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Conference.EndDate)
                    </div>

                </div>

                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.Conference.RegistrationCost, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Conference.RegistrationCost)
                    </div>
                    <div class="col-6">

                    </div>
                </div>
            </div>


        </div>
    </div>
</div>



@*--------------------------------------------------------------Application details -----------------------------------------------*@
<div class="row pt-2">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey mt-3">
            <div class="card-header">
                <h4>Application Details</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-4">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.Raw(Helper.GetIcon(Model.Status.Description)) @Html.DisplayFor(model => model.Status.Description)
                    </div>
                    <div class="col-4">
                        @Html.LabelFor(model => model.DateSubmitted, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.DateSubmitted)
                    </div>
                    <div class="col-4">
                        @Html.LabelFor(model => model.Feedback, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Feedback)
                    </div>
                    <div class="col-12">
                        <hr />
                    </div>
                </div>


                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.AttendStartDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.AttendStartDate)
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.AttendEndDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.AttendEndDate)
                    </div>
                </div>

                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.DepartureDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.DepartureDate)


                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.ReturnDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.ReturnDate)
                    </div>

                    <div class="col-12">
                        <hr />
                    </div>
                </div>

               

                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.BudgetCode, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.BudgetCode)

                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.PaymentType.Description, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.PaymentType.Description)
                    </div>
                </div>

                <div class="row pt-2">
                    <div class="col-6">
                        @Html.LabelFor(model => model.Rationale, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Html.DisplayFor(model => model.Rationale)
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.ReplStaffReq, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                        @Helper.YesNoFromBool(Model.ReplStaffReq)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*----------------------------------------Expenses -----------------------------*@
<div class="row">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey mt-3">
            <div class="card-header">
                <h4>Expenses</h4>
            </div>
            <div class="card-body">
                <div class="row">


                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.LabelFor(model => model.Expenses.SingleOrDefault().ExpenseTypeID, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                </th>
                                <th>
                                    @Html.LabelFor(model => model.Expenses.SingleOrDefault().EstimatedCost, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                </th>
                                <th>
                                    @Html.LabelFor(model => model.Expenses.SingleOrDefault().ActualCost, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                </th>
                                <th>
                                    @Html.LabelFor(model => model.Expenses.SingleOrDefault().Rationale, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Expenses)
                            {
                                var estimatedCost = item.EstimatedCost?.ToString("C");

                                if (String.IsNullOrEmpty(estimatedCost))
                                {
                                    estimatedCost = "N/A";
                                }

                                var actualCost = item.ActualCost?.ToString("C");

                                if (String.IsNullOrEmpty(actualCost))
                                {
                                    actualCost = "TBD";
                                }
                                <tr>
                                    <td>@item.ExpenseType.Description</td>
                                    <td>@estimatedCost</td>
                                    <td>
                                        @actualCost
                                    </td>
                                    <td>@item.Rationale</td>
                                </tr>
                            }
                        </tbody>
                    </table>


                </div>
            </div>

        </div>
    </div>
</div>


@*-------------------------------------------Mileages---------------------------------------------------------*@
<div class="row">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey mt-3">
            <div class="card-header">
                <h4>Mileages</h4>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.LabelFor(model => model.Mileages.SingleOrDefault().TravelDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                    </th>
                                    <th>
                                        @Html.LabelFor(model => model.Mileages.SingleOrDefault().StartAddress, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                    </th>
                                    <th>
                                        @Html.LabelFor(model => model.Mileages.SingleOrDefault().EndAddress, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                    </th>
                                    <th>
                                        @Html.LabelFor(model => model.Mileages.SingleOrDefault().Kilometres, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                    </th>
                                    <th>
                                        @Html.LabelFor(model => model.Mileages.SingleOrDefault().Status, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Mileages)
                                {
                                    <tr>
                                        <td>
                                            @item.TravelDate.ToShortDateString()
                                        </td>
                                        <td>
                                            @item.StartAddress
                                        </td>
                                        <td>
                                            @item.EndAddress
                                        </td>
                                        <td>
                                            @item.Kilometres km
                                        </td>
                                        <td>
                                            @Helper.GetIcon(item.Status.Description)
                                            @item.Status.Description
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>


                    </div>
                </div>

            </div>

        </div>
    </div>
</div>