ConferenceFormSubmittal/Models/Conference.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ConferenceFormSubmittal.Models
{
    public class Conference: IValidatableObject
    {
        public Conference()
        {
            Applications = new HashSet<Application>();
        }

        public int ID { get; set; }

        [Display(Name = "Conference")]
        [Required(ErrorMessage = "Conference Name is required.")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Conference Name must be between 5 and 100 characters in length.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Location is required.")]
        [StringLength(100)]
        public string Location { get; set; }

        [Display(Name = "Registration Cost")]
        [Required(ErrorMessage = "Registration Cost is required.")]
        [DataType(DataType.Currency)]
        public decimal RegistrationCost { get; set; }

        [Display(Name = "Start Date")]
        [Required(ErrorMessage = "Start Date is required.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [Required(ErrorMessage = "End Date is required.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime EndDate { get; set; }

        public virtual ICollection<Application> Applications { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (StartDate > EndDate)
            {
                yield return new ValidationResult("End Date cannot be before Start Date.", new[] { "EndDate" });
            }
        }
    }
}

ConferenceFormSubmittal/Controllers/ConferencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConferenceFormSubmittal.DAL;
using ConferenceFormSubmittal.Models;
using System.Data.Entity.Infrastructure;
using PagedList;

namespace ConferenceFormSubmittal.Controllers
{
    public class ConferencesController : Controller
    {
        private CFSEntities db = new CFSEntities();

        // GET: Conferences
        public ActionResult Index(string sortDirection, string sortField, string actionButton, 
            int? conferenceID, string conferenceName, string locationName, DateTime? startDate, DateTime? endDate, int? page)
        {
            IQueryable<Conference> conferences = db.Conferences;
            ViewBag.Filtering = "";

            ViewBag.ConferenceID = new SelectList(db.Conferences, "ID", "Name");
            ViewBag.Location = new SelectList(db.Conferences, "Location", "Location");

            if (!String.IsNullOrEmpty(conferenceName))
            {
                conferences = conferences.Where(p => p.Name.ToUpper().Contains(conferenceName.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastConferenceID = conferenceName;
            }

            if (!String.IsNullOrEmpty(locationName))
            {
                conferences = conferences.Where(p => p.Location.ToUpper().Contains(locationName.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastLocation = locationName;
            }

            if (startDate.HasValue && endDate.HasValue)
            {
                conferences = conferences.Where(p => p.StartDate > startDate && p.EndDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
                ViewBag.LastEndDate = endDate;
            }
            else if (startDate.HasValue && !endDate.HasValue)
            {
                conferences = conferences.Where(p => p.StartDate > startDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
            }
            else if (!startDate.HasValue && endDate.HasValue)
            {
                conferences = conferences.Where(p => p.EndDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndDate = endDate;
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = String.IsNullOrEmpty(sortDirection) ? "desc" : "";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            if (sortField == "Location")//Sorting by Location
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    conferences = conferences
                        .OrderBy(c => c.Location);
                }
                else
                {
                    conferences = conferences.OrderByDescending(c => c.Location);
                }
            }
            else if (sortField == "Registration Cost")//Sorting by Registration Cost
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    conferences = conferences
                        .OrderBy(c => c.RegistrationCost);
                }
                else
                {
                    conferences = conferences.OrderByDescending(c => c.RegistrationCost);
                }
            }
            else if (sortField == "Start Date")//Sorting by Start Date
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    conferences = conferences
                        .OrderBy(c => c.StartDate);
                }
                else
                {
                    conferences = conferences.OrderByDescending(c => c.StartDate);
                }
            }
            else if (sortField == "End Date")//Sorting by End Date
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    conferences = conferences
                        .OrderBy(c => c.EndDate);
                }
                else
                {
                    conferences = conferences.OrderByDescending(c => c.EndDate);
                }
            }
            else //By default sort by Conference
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    conferences = conferences
                        .OrderBy(c => c.Name);
                }
                else
                {
                    conferences = conferences.OrderByDescending(c => c.Name);
                }
            }
            
            ViewBag.sortField = sortField;
            ViewBag.sortDirection = sortDirection;

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(conferences.ToPagedList(pageNumber, pageSize));
        }

        // GET: Conferences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conference conference = db.Conferences.Find(id);
            if (conference == null)
            {
                return HttpNotFound();
            }
            return View(conference);
        }

        // GET: Conferences/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Conferences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Location,RegistrationCost,StartDate,EndDate")] Conference conference)
        {
            if (ModelState.IsValid)
            {
                db.Conferences.Add(conference);
                db.SaveChanges();
                return RedirectToAction("Create", "Applications", new { ConferenceID = conference.ID });
            }

            return View(conference);
        }

        // GET: Conferences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conference conference = db.Conferences.Find(id);
            if (conference == null)
            {
                return HttpNotFound();
            }
            return View(conference);
        }

        // POST: Conferences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Location,RegistrationCost,StartDate,EndDate")] Conference conference)
        {
            if (ModelState.IsValid)
            {
                db.Entry(conference).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(conference);
        }

        // GET: Conferences/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Conference conference = db.Conferences.Find(id);
            if (conference == null)
            {
                return HttpNotFound();
            }
            return View(conference);
        }

        // POST: Conferences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Conference conference = db.Conferences.Find(id);
            db.Conferences.Remove(conference);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConferenceFormSubmittal/Views/Conferences/Create.cshtml
@model ConferenceFormSubmittal.Models.Conference
@using ConferenceFormSubmittal.Utilities;
@{
    ViewBag.Title = "Create";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Create Conference</h3>
        </div>
    </div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @*---------------- Conference FORM ----------------------*@
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">

                <div class="card-header">
                    <h4>Conference</h4>
                </div>
                <div class="card-body">



                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @*---------------------ROW------------------------------------------------------------------------------------*@
                    <div class="row pt-4">

                        <div class="col-1">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label font-weight-bold" })
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter a Name" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>



                        <div class="col-1">
                            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label font-weight-bold" })
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter a Location" } })
                            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                        </div>



                        <div class="col-1">
                            @Html.LabelFor(model => model.RegistrationCost, htmlAttributes: new { @class = "control-label font-weight-bold" })
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.RegistrationCost, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter a Cost" } })
                            @Html.ValidationMessageFor(model => model.RegistrationCost, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    @*---------------------ROW------------------------------------------------------------------------------------*@
                    <div class="row pt-4">

                        <div class="col-1">
                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label font-weight-bold" })
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter a Start Date" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>



                        <div class="col-1">
                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label font-weight-bold" })
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter a End Date" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>




                        <div class="col-2">
                            <button type="submit" class="btn btn-success btn-block">
                                @Helper.GetIcon(Icons.Save)
                                Create
                            </button>
                        </div>


                        <div class="col-2">
                            <a href='@Url.Action("Index", "Conferences")' class="btn btn-primary btn-block">
                                @Helper.GetIcon(Icons.Back, 2) 
                                Go Back
                            </a>
                        </div>

                    </div>


                </div>



            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConferenceFormSubmittal/Views/Conferences/Delete.cshtml
@model ConferenceFormSubmittal.Models.Conference

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Conference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationCost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConferenceFormSubmittal/Views/Conferences/Details.cshtml
@model ConferenceFormSubmittal.Models.Conference
@using ConferenceFormSubmittal.Utilities;

@{
    ViewBag.Title = "Details";
}

<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Conference Details</h3>
        </div>
    </div>
</div>

@*//------------------------------------------------ Header buttons ---------------------------------*@
<div class="row mt-3">
    <div class="col-12">

        <div class="card bg-NCDSB-Grey">
            <div class="card-header">
                <div class="row ">
                    <div class="col-12 d-flex justify-content-between">
                        <a href='@Url.Action("Index", "Conferences")' class="btn btn-primary">
                            @Helper.GetIcon(Icons.Back)
                            Go Back
                        </a>

                        <a href='@Url.Action("Edit", "Conferences", new { id = Model.ID })' class="btn btn-info">
                            @Helper.GetIcon(Icons.Edit)
                            Edit
                        </a>

                        <a href='@Url.Action("Delete", "Conferences", new { id = Model.ID })' class="btn btn-danger">
                            @Helper.GetIcon(Icons.Flag)
                            Flag
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="row pt-3">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey">
            <div class="card-header">
                <h4>Conference Details</h4>
            </div>

            <div class="card-body">

                @*---------------------ROW------------------------------------------------------------------------------------*@
                <div class="row pt-4">

                    <div class="col-1">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label font-weight-bold" })
                    </div>
                    <div class="col-3">
                        @Html.DisplayFor(model => model.Name)
                    </div>



                    <div class="col-1">
                        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label font-weight-bold" })
                    </div>
                    <div class="col-3">
                        @Html.DisplayFor(model => model.Location)
                    </div>



                    <div class="col-1">
                        @Html.LabelFor(model => model.RegistrationCost, htmlAttributes: new { @class = "control-label font-weight-bold" })
                    </div>
                    <div class="col-3">
                        @Html.DisplayFor(model => model.RegistrationCost)
                    </div>
                </div>


                @*---------------------ROW------------------------------------------------------------------------------------*@
                <div class="row pt-4">

                    <div class="col-1">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label font-weight-bold" })
                    </div>
                    <div class="col-3">
                        @Html.DisplayFor(model => model.StartDate)
                    </div>



                    <div class="col-1">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label font-weight-bold" })
                    </div>
                    <div class="col-3">
                        @Html.DisplayFor(model => model.EndDate)
                    </div>


                </div>


            </div>



        </div>
    </div>
</div>

ConferenceFormSubmittal/Views/Conferences/Index.cshtml
@model PagedList.IPagedList<ConferenceFormSubmittal.Models.Conference>
@using ConferenceFormSubmittal.Utilities;
@using PagedList.Mvc;


@{
    ViewBag.Title = "Index";
}


<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Conferences</h3>
        </div>
    </div>
</div>

@using (Html.BeginForm("Index", "Conferences", FormMethod.Get))
{
    //Filter
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">

                <div class="card-header d-flex justify-content-between ">
                    <a href='@Url.Action("Index", "Home")' class="btn btn-primary">
                        @Helper.GetIcon(Icons.Back) Go Back
                    </a>

                    <a href='@Url.Action("Create", "Conferences")' class="btn btn-primary">
                        @Helper.GetIcon(Icons.Create) Add a Conference
                    </a>

                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=".filter" aria-expanded="false" aria-controls="filter">
                        @Helper.GetIcon(Icons.Filter) Filter
                    </button>
                </div>

                <div class="collapse filter">
                    <div class="card-body">

                        <div class="row">
                            <div class="col-6">
                                <label class="font-weight-bold d-block"> Conference </label>
                                @Html.TextBox("ConferenceName", null, new { @class = "form-control bg-NCDSB-GreyLight" })

                                <label class="font-weight-bold d-block"> Location </label>
                                @Html.TextBox("LocationName", null, new { @class = "form-control bg-NCDSB-GreyLight" })

                            </div>
                            <div class="col-6">
                                <label class="font-weight-bold d-block"> Start Date </label>
                                @Html.TextBox("startDate", null, new { @class = "form-control datepicker bg-NCDSB-GreyLight", @type = "date" })
                                <label class="font-weight-bold d-block"> End Date </label>
                                @Html.TextBox("endDate", null, new { @class = "form-control datepicker bg-NCDSB-GreyLight", @type = "date" })

                            </div>

                        </div>
                    </div>

                    <div class="card-footer">
                        <button class="btn btn-primary" type="submit" name="actionButton">
                            @Helper.GetIcon(Icons.Filter) Filter
                        </button>

                        <a href='@Url.Action("Index", "Conferences")' class="btn btn-danger">
                            @Helper.GetIcon(Icons.Eraser) Clear
                        </a>
                    </div>

                </div>

            </div>
        </div>
    </div>
    //Filter

    <div class="row pt-3">

        <div class="col-12">
            <!--Panel-->
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">
                    <h4>Conferences</h4>
                </div>

                <div class="card-body">
                    <table class="table">
                        <tr>
                            <th>
                                <input type="submit" name="actionButton" value="Conference" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Location" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Registration Cost" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Start Date" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="End Date" class="btn btn-grey btn-md" />
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RegistrationCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>

                        <a href='@Url.Action("Details", "Conferences", new { id = item.ID })' class="badge badge-primary">
                            @Helper.GetIcon(Icons.View, 3)
                            <br />
                            View
                        </a>
                        <a href='@Url.Action("Edit", "Conferences", new { id = item.ID })' class="badge badge-info">
                            @Helper.GetIcon(Icons.Edit, 3)
                            <br />
                            Edit
                        </a>

                        <a href='@Url.Action("Delete", "Conferences", new { id = item.ID })' class="badge badge-danger">
                            @Helper.GetIcon(Icons.Flag, 3)
                            <br />
                            Flag
                        </a>


                        <a href='~/Applications/Create?ConferenceID=@item.ID' class="badge badge-success">
                            @Helper.GetIcon(Icons.Check, 3)
                            <br />
                            Select
                        </a>

                    </td>
                </tr>
}
                    </table>
                    <span id="filterMessage" class="text-danger">@((Model.Count() == 0) ? "No results match your criteria. Can't find the conference you're looking for? Click \"ADD A CONFERENCE\"." : "")</span>
                    <input type="hidden" name="sortDirection" value="@ViewBag.sortDirection" />
                    <input type="hidden" name="sortField" value="@ViewBag.sortField" />



                    <label class="font-weight-bold">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                        @Html.PagedListPager(Model, page => Url.Action("Index",
     new
     {
         page,
         sortDirection = ViewBag.sortDirection,
         sortField = ViewBag.sortField,
         conferenceID = ViewBag.LastConferenceID,
         location = ViewBag.LastLocation,
         startDate = ViewBag.LastStartDate,
         endDate = ViewBag.LastEndDate
     }))
                    </label>
                </div>

               

            </div>

        </div>
    </div>
}