ConferenceFormSubmittal/Models/Site.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ConferenceFormSubmittal.Models
{
    public class Site : Auditable
    {
        public int ID { get; set; }

        [Display(Name = "Site Name")]
        [Required(ErrorMessage = "Site Name is required.")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Site Name must be between 5 and 100 characters in length.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Address is required.")]
        [StringLength(100)]
        public string Address { get; set; }
    }
}

ConferenceFormSubmittal/Controllers/SitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConferenceFormSubmittal.DAL;
using ConferenceFormSubmittal.Models;

namespace ConferenceFormSubmittal.Controllers
{
    public class SitesController : Controller
    {
        private CFSEntities db = new CFSEntities();

        // GET: Sites
        public ActionResult Index()
        {
            return View(db.Sites.ToList());
        }

        // GET: Sites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site = db.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        // GET: Sites/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address")] Site site)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(site).State = EntityState.Added;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty, "The record you attempted to edit " + "was modified by another user. Please go back and refresh");
            }

            return View(site);
        }

        // GET: Sites/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site = db.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        // POST: Sites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Byte[] RowVersion, [Bind(Include = "ID,Name,Address")] Site site)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(site).State = EntityState.Modified;
                    db.Entry(site).OriginalValues["RowVersion"] = RowVersion;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty, "The record you attempted to edit " + "was modified by another user. Please go back and refresh");
            }

            return View(site);
        }

        // GET: Sites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site = db.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        // POST: Sites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Site site = db.Sites.Find(id);
            db.Sites.Remove(site);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ConferenceFormSubmittal/Views/Sites/Create.cshtml
@model ConferenceFormSubmittal.Models.Site
@using ConferenceFormSubmittal.Utilities;

@{
    ViewBag.Title = "Create";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Create Site</h3>
        </div>
    </div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()




    //------------------------------------------------------------------buttons bar--------------------------------------
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">

                    <div class="col-12 d-flex justify-content-between">

                        <a href='@Url.Action("Index", "Sites")' class="btn btn-primary">
                            @Helper.GetIcon(Icons.Back)
                            Go Back
                        </a>

                        <button type="submit" class="btn btn-success">
                            @Helper.GetIcon(Icons.Save)
                            Create
                        </button>
                    </div>


                </div>
            </div>
        </div>

    </div>


    //--------------------------------------------------------------- Create -------------------------------------------
    <div class="row pt-3">
        <div class="col-8">
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">
                    <h4>Site</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                           
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>                 
                        </div>
                       
                    </div>
                    <div class="row">
                        <div class="col-12">
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @id = "txtAddress", @placeholder = "Enter An Address" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <a onclick="GetRoute()" class="btn btn-success d-block">
                                <i class="fa fa-map-marker fa-2x"></i>
                                Get Route
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @*------------------------------ google map --------------------------------*@
        <div class="col-4">
            <div class="card bg-NCDSB-Grey">
                <div class="card-body">
                    <div class="col-12">
                        <div id="dvMap" style="min-height:400px"></div>
                    </div>

                </div>
            </div>
        </div>

    </div>


}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQoBa1Dcsary4e_iMueoDfG8taMDb8IKI&libraries=places" type="text/javascript"></script>

    <script>

        var address = document.getElementById('txtAddress');
        var geocoder = new google.maps.Geocoder();

        var map = new google.maps.Map(document.getElementById('dvMap'), {
            center: { lat: 43.002662, lng: -79.2554264 },
            zoom: 15,
            mapTypeId: 'roadmap'
        });

        google.maps.event.addDomListener(window, 'load', function () {
            new google.maps.places.SearchBox(document.getElementById('txtAddress'));
        });

        function GetRoute() {
            address = document.getElementById('txtAddress').value;
            geocoder = new google.maps.Geocoder();
            if (geocoder) {
                geocoder.geocode({
                    'address': address
                }, function (results, status) {
                    if (status == google.maps.GeocoderStatus.OK) {
                        if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
                            map.setCenter(results[0].geometry.location);

                            var infowindow = new google.maps.InfoWindow({
                                content: '<b>' + address + '</b>',
                                size: new google.maps.Size(150, 50)
                            });

                            var marker = new google.maps.Marker({
                                position: results[0].geometry.location,
                                map: map,
                                title: address
                            });
                            google.maps.event.addListener(marker, 'click', function () {
                                infowindow.open(map, marker);
                            });

                        } else {
                            alert("No results found");
                        }
                    } else {
                        alert("Geocode was not successful for the following reason: " + status);
                    }
                });
            }
        }

                    //map.addListener('click', function () {
                    //    map.setZoom(8);
                    //    map.setCenter(marker.getPosition());
                    //});

                    //var address = "San Diego, CA";

                    //function location() {
                    //    geocoder = new google.maps.Geocoder();
                    //    if (geocoder) {
                    //        geocoder.geocode({
                    //            'address': address
                    //        }, function (results, status) {
                    //            if (status == google.maps.GeocoderStatus.OK) {
                    //                if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
                    //                    map.setCenter(results[0].geometry.location);

                    //                    var infowindow = new google.maps.InfoWindow({
                    //                        content: '<b>' + address + '</b>',
                    //                        size: new google.maps.Size(150, 50)
                    //                    });

                    //                    var marker = new google.maps.Marker({
                    //                        position: results[0].geometry.location,
                    //                        map: map,
                    //                        title: address
                    //                    });
                    //                    google.maps.event.addListener(marker, 'click', function () {
                    //                        infowindow.open(map, marker);
                    //                    });

                    //                } else {
                    //                    alert("No results found");
                    //                }
                    //            } else {
                    //                alert("Geocode was not successful for the following reason: " + status);
                    //            }
                    //        });
                    //    }
                    //}

    </script>
}

ConferenceFormSubmittal/Views/Sites/Delete.cshtml
@model ConferenceFormSubmittal.Models.Site

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Site</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConferenceFormSubmittal/Views/Sites/Details.cshtml
@model ConferenceFormSubmittal.Models.Site

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Site</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ConferenceFormSubmittal/Views/Sites/Edit.cshtml
@model ConferenceFormSubmittal.Models.Site
@using ConferenceFormSubmittal.Utilities;

@{
    ViewBag.Title = "Edit";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Create Site</h3>
        </div>
    </div>
</div>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    //------------------------------------------------------------------buttons bar--------------------------------------
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">          
                <div class="card-header">
                    <div class="row">
                        <div class="col-12 d-flex justify-content-between">

                            <a href='@Url.Action("Index", "Sites")' class="btn btn-primary">
                                @Helper.GetIcon(Icons.Back)
                                Go Back
                            </a>

                            <button type="submit" class="btn btn-success">
                                @Helper.GetIcon(Icons.Save)
                                Save
                            </button>
                        </div>
                    </div>               
                </div>
            </div>
        </div>
    </div>

    //--------------------------------------------------------------- Create -------------------------------------------
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">
                    <h4>Site</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ID)

                        </div>

                    </div>
                    <div class="row">
                        <div class="col-12">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control bg-NCDSB-GreyLight" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control bg-NCDSB-GreyLight" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ConferenceFormSubmittal/Views/Sites/Index.cshtml
@model IEnumerable<ConferenceFormSubmittal.Models.Site>
@using ConferenceFormSubmittal.Utilities;

@{
    ViewBag.Title = "Index";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Sites</h3>
        </div>
    </div>
</div>

<div class="row pt-3">
    <div class="col-12">

        <div class="card bg-NCDSB-Grey">
            <div class="card-header d-flex justify-content-between">

                <a href='@Url.Action("Index", "Home")' class="btn btn-primary">
                    @Helper.GetIcon(Icons.Back) Go Back
                </a>

                <a href='@Url.Action("Create", "Sites")' class="btn btn-primary">
                    @Helper.GetIcon(Icons.Create) Create New
                </a>

                <a href='#' class="btn btn-primary">
                    @Helper.GetIcon(Icons.Filter) Filter
                </a>
            </div>
        </div>

    </div>
</div>


@*--------------------------Sites ----------------------------------------*@
<div class="row pt-3">
    <div class="col-12">
        <div class="card bg-NCDSB-Grey">
            <div class="card-header">
                <h4>Sites</h4>

            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <table class="table">
                            <tr>
                                <th>
                                    <button class="btn btn-grey btn-md">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </button>
                                </th>
                                <th>                     
                                    <button class="btn btn-grey btn-md">
                                        @Html.DisplayNameFor(model => model.Address)
                                    </button>
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
        {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td class="float-right">
                            @*<a href='@Url.Action("Details", "Sites", new { id = item.ID })' class="badge badge-success bg-NCDSB-myGreen hoverable text-white">
                                @Helper.GetIcon(Icons.View, 3)
                                <br />
                                Details
                            </a>*@

                            <a href='@Url.Action("Edit", "Sites", new { id = item.ID })' class="badge badge-info">
                                @Helper.GetIcon(Icons.Edit, 3)
                                <br />
                                Edit
                            </a>

                            <a href='#'  class="badge badge-danger">
                                @Helper.GetIcon(Icons.Flag, 3)
                                <br />
                                Flag
                            </a>



                        </td>
                    </tr>
}

                        </table>

                    </div>


                </div>


            </div>
            
        </div>



    </div>


</div>