ConferenceFormSubmittal/Models/Mileage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ConferenceFormSubmittal.Models
{
    public class Mileage
    {
        public int ID { get; set; }

        [Display(Name = "Date of Travel")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime TravelDate { get; set; }

        [Display(Name = "Starting Address")]
        [Required(ErrorMessage = "Starting Address is required.")]
        [StringLength(100)]
        public string StartAddress { get; set; }

        [Display(Name = "Destination Address")]
        [Required(ErrorMessage = "Destination Address is required.")]
        [StringLength(100)]
        public string EndAddress { get; set; }

        [Display(Name = "Round Trip")]
        public bool RoundTrip { get; set; }

        // to be calculated
        [Display(Name = "Distance")]
        public decimal Kilometres { get; set; }

        [StringLength(500, ErrorMessage = "Feedback may include no more than 500 characters.")]
        public string Feedback { get; set; }

        public int StatusID { get; set; }

        public int EmployeeID { get; set; }

        public int? ApplicationID { get; set; }

        public virtual Status Status { get; set; }

        public virtual Employee Employee { get; set; }

        [Display(Name = "Conference")]
        public virtual Application Application { get; set; }
    }
}

ConferenceFormSubmittal/Controllers/MileagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ConferenceFormSubmittal.DAL;
using ConferenceFormSubmittal.Models;
using System.Data.Entity.Infrastructure;
using PagedList;

namespace ConferenceFormSubmittal.Controllers
{
    public class MileagesController : Controller
    {
        private CFSEntities db = new CFSEntities();

        // GET: Mileages
        public ActionResult Index(string sortDirection, string sortField, string actionButton,
            int? employeeID, string employeeFirst, string employeeLast, string startAddress, 
            string endAddress, DateTime? startDate, DateTime? endDate, int? statusID, int? page)
        {
            PopulateDropDownLists();
            var mileages = db.Mileages.Include(m => m.Application).Include(m => m.Employee).Include(m => m.Status);
            ViewBag.Filtering = "";
            
            if (employeeID.HasValue)
            {
                mileages = mileages.Where(p => p.EmployeeID == employeeID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeID = employeeID;
            }
            if (!String.IsNullOrEmpty(employeeFirst))
            {
                mileages = mileages.Where(p => p.Employee.FirstName.ToUpper().Contains(employeeFirst.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeFirst = employeeFirst;
            }
            if (!String.IsNullOrEmpty(employeeLast))
            {
                mileages = mileages.Where(p => p.Employee.LastName.ToUpper().Contains(employeeLast.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeLast = employeeLast;
            }
            if (!String.IsNullOrEmpty(startAddress))
            {
                mileages = mileages.Where(p => p.StartAddress.ToUpper().Contains(startAddress.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartAddress = startAddress;
            }
            if (!String.IsNullOrEmpty(endAddress))
            {
                mileages = mileages.Where(p => p.EndAddress.ToUpper().Contains(endAddress.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndAddress = endAddress;
            }
            if (startDate.HasValue && endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate > startDate && p.TravelDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
                ViewBag.LastEndDate = endDate;
            }
            else if (startDate.HasValue && !endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate > startDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
            }
            else if (!startDate.HasValue && endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndDate = endDate;
            }
            if (statusID.HasValue)
            {
                mileages = mileages.Where(p => p.StatusID == statusID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStatusID = statusID;
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = String.IsNullOrEmpty(sortDirection) ? "desc" : "";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            if (sortField == "Start Address")//Sorting by Start Location
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    mileages = mileages
                        .OrderBy(c => c.StartAddress);
                }
                else
                {
                    mileages = mileages.OrderByDescending(c => c.StartAddress);
                }
            }
            else if (sortField == "End Address")//Sorting by End Location
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    mileages = mileages
                        .OrderBy(c => c.EndAddress);
                }
                else
                {
                    mileages = mileages.OrderByDescending(c => c.EndAddress);
                }
            }
            else if(sortField == "Kilometres")//Sorting by Kilometres
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    mileages = mileages
                        .OrderBy(c => c.Kilometres);
                }
                else
                {
                    mileages = mileages.OrderByDescending(c => c.Kilometres);
                }
            }
            else if (sortField == "Travel Date")//Sorting by Status
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    mileages = mileages
                        .OrderBy(p => p.TravelDate);
                }
                else
                {
                    mileages = mileages
                        .OrderByDescending(p => p.TravelDate);
                }
            }
            else //By default sort by Travel Date
            {
                if (String.IsNullOrEmpty(sortDirection))
                {
                    mileages = mileages
                        .OrderBy(c => c.StatusID);
                }
                else
                {
                    mileages = mileages.OrderByDescending(c => c.StatusID);
                }
            }

            ViewBag.sortField = sortField;
            ViewBag.sortDirection = sortDirection;

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(mileages.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult IndexAdmin(string sortDirection, string sortField, string actionButton,
            int? employeeID, string employeeFirst, string employeeLast, string startAddress,
            string endAddress, DateTime? startDate, DateTime? endDate, int? statusID, int? page)
        {
            PopulateDropDownLists();
            var mileages = db.Mileages.Include(m => m.Application).Include(m => m.Employee).Include(m => m.Status);
            ViewBag.Filtering = "";

            if (employeeID.HasValue)
            {
                mileages = mileages.Where(p => p.EmployeeID == employeeID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeID = employeeID;
            }
            if (!String.IsNullOrEmpty(employeeFirst))
            {
                mileages = mileages.Where(p => p.Employee.FirstName.ToUpper().Contains(employeeFirst.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeFirst = employeeFirst;
            }
            if (!String.IsNullOrEmpty(employeeLast))
            {
                mileages = mileages.Where(p => p.Employee.LastName.ToUpper().Contains(employeeLast.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEmployeeLast = employeeLast;
            }
            if (!String.IsNullOrEmpty(startAddress))
            {
                mileages = mileages.Where(p => p.StartAddress.ToUpper().Contains(startAddress.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartAddress = startAddress;
            }
            if (!String.IsNullOrEmpty(endAddress))
            {
                mileages = mileages.Where(p => p.EndAddress.ToUpper().Contains(endAddress.ToUpper()));
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndAddress = endAddress;
            }
            if (startDate.HasValue && endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate > startDate && p.TravelDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
                ViewBag.LastEndDate = endDate;
            }
            else if (startDate.HasValue && !endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate > startDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStartDate = startDate;
            }
            else if (!startDate.HasValue && endDate.HasValue)
            {
                mileages = mileages.Where(p => p.TravelDate < endDate);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastEndDate = endDate;
            }
            if (statusID.HasValue)
            {
                mileages = mileages.Where(p => p.StatusID == statusID);
                ViewBag.Filtering = " in";//Flag filtering
                ViewBag.LastStatusID = statusID;
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                //Reset paging if ANY button was pushed
                page = 1;

                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {

ConferenceFormSubmittal/Views/Mileages/Delete.cshtml
@model ConferenceFormSubmittal.Models.Mileage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mileage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Application.Rationale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Application.Rationale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kilometres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kilometres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Feedback)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Feedback)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ConferenceFormSubmittal/Views/Mileages/EditAdmin.cshtml
@model ConferenceFormSubmittal.Models.Mileage
@using ConferenceFormSubmittal.Utilities;
@{
    ViewBag.Title = "Edit";
}

<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">Edit Mileage</h3>
        </div>
    </div>
</div>



@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmEditMileageAdmin" }))
{
    @Html.AntiForgeryToken()

    @*---------------------ROW--APPROVAL BAR----------------------------------------------*@
    <div class="row pt-3">
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">
                    <div class="row">
                        <div class="col-12 d-flex justify-content-between">

                            <a href='@Url.Action("IndexAdmin", "Mileages")' class="btn btn-primary">
                                @Helper.GetIcon(Icons.Back) Go Back
                            </a>

                            <button id="btnApprove" type="button" value="Approve" class="btn btn-success">
                                @Helper.GetIcon(Icons.Approved) Approve
                            </button>

                            <button id="btnDeny" type="button" value="Deny" class="btn btn-danger ">
                                @Helper.GetIcon(Icons.Denied) Deny
                            </button>

                            @Html.EditorFor(model => model.EmployeeID, new { htmlAttributes = new { @class = "form-control", @id = "txtEmployeeID", @Value = "1", @hidden = "hidden" } })
                            @Html.EditorFor(model => model.StatusID, new { htmlAttributes = new { @class = "form-control", @id = "txtStatusID", @hidden = "hidden" } })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <div class="row pt-3">


        @*---------------------Edit Form------------------------------------------------------------------------------------*@
        <div class="col-12">
            <div class="card bg-NCDSB-Grey">
                <div class="card-header">
                    <h3>Conference Details</h3>
                    @*@Html.LabelFor(model => model.Application.Conference.Name, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })*@
                    @Html.DisplayFor(model => model.Application.Conference.Name)
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            @Html.EditorFor(model => model.ApplicationID, new { htmlAttributes = new { @class = "form-control bg-NCDSB-GreyLight", @hidden = "hidden" } })
                            @Html.LabelFor(model => model.Application.Conference.Name, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.DisplayFor(model => model.Application.Conference.Name)
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.Application.Conference.Location, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.DisplayFor(model => model.Application.Conference.Location)
                        </div>
                        <div class="col-12">
                            <hr />
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.Application.DepartureDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.DisplayFor(model => model.Application.DepartureDate)
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.Application.ReturnDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.DisplayFor(model => model.Application.ReturnDate)
                        </div>
                        <div class="col-12">
                            <hr />
                        </div>
                          @*---------------------ROW------------------------------------------------------------------------------------*@
                        <div class="col-6">
                            @Html.LabelFor(model => model.StartAddress, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.EditorFor(model => model.StartAddress, new { htmlAttributes = new { @class = "form-control", @id = "txtStartAddress", @hidden = "hidden" } })
                            @Html.DisplayFor(model => model.StartAddress)
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.EndAddress, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.EditorFor(model => model.EndAddress, new { htmlAttributes = new { @class = "form-control", @id = "txtEndAddress", @hidden = "hidden" } })
                            @Html.DisplayFor(model => model.EndAddress)
                        </div>
                        <div class="col-12">
                            <hr />
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.TravelDate, htmlAttributes: new { @class = "control-label d-block font-weight-bold" })
                            @Html.EditorFor(model => model.TravelDate, new { htmlAttributes = new { @class = "form-control", @hidden = "hidden" } })
                            @Html.DisplayFor(model => model.TravelDate)
                        </div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.RoundTrip, htmlAttributes: new { @class = "control-label  d-block font-weight-bold" })
                            @Html.EditorFor(model => model.RoundTrip, new { htmlAttributes = new { @class = "form-control bg-NCDSB-GreyLight d-none", @id = "chkRoundTrip" } })
                            @Html.DisplayFor(model => model.RoundTrip)
                        </div>

                    </div>



                    @*---------------------ERROR MESSAGES ---------------------*@
                    <div class="row pt-3">
                        <div class="col-12">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ID)
                        </div>
                    </div>


                </div>

                <div class="card-footer rgba-grey-light">
                    @*---------------------ROW------------------------------------------------------------------------------------*@
                    <div class="row pt-3 ">
                        <div class="col-2">
                            <label" class="font-weight-bold">Kilometers</label">
                        </div>
                        <div class="col-3">
                            @Html.EditorFor(model => model.Kilometres, new
                            {
                                htmlAttributes = new
                                {
                                    @class = "form-control text-dark",
                                    @id = "txtKilometres",
                                    @hidden = "hidden"
                                }
                            })
                            @Html.DisplayFor(model => model.Kilometres)
                            @Html.ValidationMessageFor(model => model.Kilometres, "", new { @class = "text-danger" })

                        </div>
                        <div class="col-2">
                            <label class="font-weight-bold">Mileage Claim</label>
                        </div>
                        <div class="col-3">
                            <input class="form-control text-dark" type="text" id="txtReimbursement" disabled="disabled" />
                        </div>
                    </div>


                </div>

            </div>

        </div>
    </div>



}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("#btnApprove").click(function () {
            var $status = $("#txtStatusID");

            if (confirm("Do you want to approve this Mileage Application?")) {
                $status.val(2);
                document.getElementById("frmEditMileageAdmin").submit();
            }
        });

        $("#btnDeny").click(function () {
            var $status = $("#txtStatusID");

            if (confirm("Do you want to deny this Mileage Application?")) {
                $status.val(3);
                document.getElementById("frmEditMileageAdmin").submit();
            }
        });

        window.onload = function () {
            var txtMileage = document.getElementById("txtKilometres").value
            var txtReimbursement = document.getElementById("txtReimbursement");

            document.getElementById("txtReimbursement").value = (txtMileage / 2).toFixed(2);

        }
    </script>
}

ConferenceFormSubmittal/Views/Mileages/Index.cshtml
@model PagedList.IPagedList<ConferenceFormSubmittal.Models.Mileage>
@using ConferenceFormSubmittal.Utilities;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}




<!--HEADING-->
<div class="row pt-3">
    <div class="col-12">
        <div class="card card-header bg-NCDSB-Grey">
            <h3 class="text-center font-weight-bold">My Mileage</h3>
        </div>
    </div>
</div>


@using (Html.BeginForm("Index", "Mileages", FormMethod.Get))
{
    //--------------Filter bar ---------------------
    <div class="row pt-3">
        <div class="col-12">

            @*---------------FILTER CARD -------------------*@
            <div class="card bg-NCDSB-Grey">
                <div class="card-header d-flex justify-content-between ">

                    <a href='@Url.Action("Index", "Home")' class="btn btn-primary">
                        @Helper.GetIcon(Icons.Back) Go Back
                    </a>

                    <a href='@Url.Action("Create", "Mileages")' class="btn btn-primary">
                        <i class="fa fa-file-text fa-2x" aria-hidden="true"></i> Create New
                    </a>

                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target=".filter" aria-expanded="false" aria-controls="collapseExample,collapseExamples">
                        @Helper.GetIcon(Icons.Filter) Filter
                    </button>
                </div>

                <div class="collapse filter">

                    <div class="card-body">

                        <div class="row">

                            <div class="col-4">
                                <label class="font-weight-bold">Start Address</label>
                                @Html.TextBox("startAddress", null, new { @class = "form-control bg-NCDSB-GreyLight" })

                                <label class="font-weight-bold">End Address</label>
                                @Html.TextBox("endAddress", null, new { @class = "form-control bg-NCDSB-GreyLight" })
                            </div>

                            <div class="col-4">
                                <label class="font-weight-bold">Date After:</label>
                                @Html.TextBox("startDate", null, new { @class = "form-control datepicker bg-NCDSB-GreyLight", @type = "date" })

                                <label class="font-weight-bold">Date Before:</label>
                                @Html.TextBox("endDate", null, new { @class = "form-control datepicker bg-NCDSB-GreyLight", @type = "date" })
                            </div>

                            <div class="col-4">
                                <b>Status</b>
                                @Html.DropDownList("StatusID", null, "All Statuses", htmlAttributes: new { @class = "form-control bg-NCDSB-GreyLight" })
                            </div>

                        </div>

                    </div>

                    <div class="card-footer">
                        <button class="btn btn-primary" type="submit" name="actionButton">
                            @Helper.GetIcon(Icons.Filter) Filter
                        </button>

                        <a href='@Url.Action("Index", "Mileages")' class="btn btn-danger">
                            @Helper.GetIcon(Icons.Eraser) Clear
                        </a>
                    </div>
                </div>



            </div>

        </div>
    </div>


    //--------------Mileages bar ---------------------
    <div class="row pt-3">
        <div class="col-12">
            <div class="card  bg-NCDSB-Grey ">
                <div class="card-header">
                    <h4>Mileages</h4>
                </div>

                <div class="card-body">
                    <table class="table">
                        <tr>

                            <th>
                                <input type="submit" name="actionButton" value="Start Address" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="End Address" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Kilometres" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Travel Date" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Round Trip" disabled="disabled" class="btn btn-grey btn-md" />
                            </th>
                            <th>
                                <input type="submit" name="actionButton" value="Status" class="btn btn-grey btn-md" />
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr class=@Helper.GetBackGround(item.Status.Description)>

                                <td>
                                    @Html.DisplayFor(modelItem => item.StartAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EndAddress)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Kilometres) Km
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TravelDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RoundTrip)
                                </td>
                                <td>
                                    @Helper.GetIcon(item.Status.Description)
                                    @Html.DisplayFor(modelItem => item.Status.Description)
                                </td>

                                <td>

                                    @*<a href='@Url.Action("Details", "Mileages", new { id = item.ID })' class="badge badge-primary">
                                            @Helper.GetIcon(Icons.View, 3)
                                            <br />
                                            View
                                        </a>*@
                                    <a href='@Url.Action("Edit", "Mileages", new { id = item.ID })' class="badge badge-info">
                                        @Helper.GetIcon(Icons.Edit, 3)
                                        <br />
                                        Edit
                                    </a>
                                    <a href='@Url.Action("Delete", "Mileages", new { id = item.ID })' class="badge badge-danger">
                                        @Helper.GetIcon(Icons.Flag, 3)
                                        <br />
                                        Flag
                                    </a>

                                </td>
                            </tr>
                        }

                    </table>
                    <span id="filterMessage" class="text-danger">@((Model.Count() == 0) ? "Zero applicaitons found.  No records match your criteria." : "")</span>
                    <input type="hidden" name="sortDirection" value="@ViewBag.sortDirection" />
                    <input type="hidden" name="sortField" value="@ViewBag.sortField" />


                    <label class="font-weight-bold">
                        <label class="font-weight-bold">
                            Page  @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)  of @Model.PageCount
                            @Html.PagedListPager(Model, page => Url.Action("Index",
new
{
page,
sortDirection = ViewBag.sortDirection,
sortField = ViewBag.sortField,
employeeID = ViewBag.LastEmployeeID,
employeeFirst = ViewBag.LastEmployeeFirst,
employeeLast = ViewBag.LastEmployeeLast,
startAddress = ViewBag.LastStartAddress,
endAddress = ViewBag.LastEndAddress,
startDate = ViewBag.LastStartDate,
endDate = ViewBag.LastEndDate,
statusID = ViewBag.LastStatusID
}))
                        </label>
                    </label>
                </div>



            </div>
        </div>

    </div>



}